# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b10abf367db9b41b11a7ad89c18503fd715b5a4eebe143156d530146d794346fe7d67ab595f0883d7c628300387f2f22644b09576a0d2694bb4339e0cd51099

test:
  secret_key_base: b64837ff8681d1c6eae5fccf4424feeb5de7c6ca0f6ad9168860c9040daf6bb3262760510fec5e82959603086770236101d196855a77b202c0af3e1816fe87dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
